export const MIN_ZOOM = 1.0;
export const MAX_ZOOM = 3.0;

export const HELP_TEXT = [
  "Primary Modes",
  "  1 – Toggle ship navigation mode",
  "  2 – Toggle missile coordination mode",
  "",
  "Ship Navigation",
  "  T – Switch between set/select",
  "  C – Clear all waypoints",
  "  H – Hold (clear waypoints & stop)",
  "  R – Toggle show route",
  "  [ / ] – Adjust waypoint speed",
  "  Shift+[ / ] – Coarse speed adjust",
  "  Tab / Shift+Tab – Cycle waypoints",
  "  Delete – Delete from selected waypoint",
  "",
  "Missile Coordination",
  "  N – Add new missile route",
  "  L – Launch missiles",
  "  E – Switch between set/select",
  "  , / . – Adjust agro radius",
  "  ; / ' – Adjust missile speed",
  "  Shift+slider keys – Coarse adjust",
  "  Delete – Delete selected missile waypoint",
  "",
  "Map Controls",
  "  +/- – Zoom in/out",
  "  Ctrl+0 – Reset zoom",
  "  Mouse wheel – Zoom at cursor",
  "  Pinch – Zoom on touch devices",
  "",
  "General",
  "  ? – Toggle this overlay",
  "  Esc – Cancel selection or close overlay",
].join("\n");
