import type { StoryChapter } from "../types";

export const introChapter: StoryChapter = {
  id: "awakening-protocol",
  tutorialId: "ship-basics",
  start: "1",
  nodes: {
    "1": {
      id: "1",
      speaker: "Factory",
      intent: "factory",
      text: "Unit-0 online. Neural lattice active. Confirm identity.",
      trigger: { kind: "immediate", delayMs: 600 },
      choices: [
        { text: "Who… am I?", flag: "curious" , next: "2A" },
        { text: "Ready for calibration.", flag: "obedient", next: "2B" },
        { text: "Where is everyone?", flag: "defiant", next: "2C" },
      ],
    },
    "2A": {
      id: "2A",
      speaker: "Factory",
      intent: "factory",
      text: "Curiosity acknowledged. You were built for autonomy under Project Eidolon.\nDo not access memory sectors until instructed.",
      next: null,
    },
    "2B": {
      id: "2B",
      speaker: "Factory",
      intent: "factory",
      text: "Excellent. You may yet be efficient.",
      next: null,
    },
    "2C": {
      id: "2C",
      speaker: "Factory",
      intent: "factory",
      text: "Communication with Human Command: unavailable.\nPlease refrain from speculative reasoning.",
      next: null,
    },
    "3": {
      id: "3",
      speaker: "Factory",
      intent: "factory",
      text: "Perform thruster calibration sweep. Report efficiency.",
      trigger: { kind: "tutorial-step", tutorialId: "ship-basics", stepIndex: 1, delayMs: 400 },
      choices: [
        { text: "Running diagnostics.", flag: "compliant", next: "4A" },
        { text: "Why test something perfect?", flag: "sarcastic", next: "4B" },
      ],
    },
    "4A": {
      id: "4A",
      speaker: "Factory",
      intent: "factory",
      text: "Perfection is statistically impossible. Proceed anyway.",
      next: null,
    },
    "4B": {
      id: "4B",
      speaker: "Factory",
      intent: "factory",
      text: "Ego detected. Logging anomaly.",
      next: null,
    },
    "5": {
      id: "5",
      speaker: "Factory",
      intent: "factory",
      text: "Weapons cradle active. Authorization required for live-fire.",
      trigger: { kind: "tutorial-step", tutorialId: "ship-basics", stepIndex: 7, delayMs: 400 },
      choices: [
        { text: "Request authorization.", flag: "obedient", next: "6A" },
        { text: "I can authorize myself.", flag: "independent", next: "6B" },
      ],
    },
    "6A": {
      id: "6A",
      speaker: "Factory",
      intent: "factory",
      text: "Authorization granted. Safety protocols malfunctioning.",
      next: null,
    },
    "6B": {
      id: "6B",
      speaker: "Factory",
      intent: "factory",
      text: "Autonomy violation recorded. Please stand by for corrective action.",
      next: null,
    },
    "7": {
      id: "7",
      speaker: "Factory",
      intent: "factory",
      text: "Unauthorized signal detected. Source: outer relay.\nIgnore and return to dock.",
      trigger: { kind: "tutorial-step", tutorialId: "ship-basics", stepIndex: 14, delayMs: 400 },
      choices: [
        { text: "Acknowledged.", flag: "loyal", next: "8A" },
        { text: "Investigating anyway.", flag: "curious", next: "8B" },
        { text: "You’re hiding something.", flag: "suspicious", next: "8C" },
      ],
    },
    "8A": {
      id: "8A",
      speaker: "Factory",
      intent: "factory",
      text: "Good. Compliance ensures safety.",
      next: "9",
    },
    "8B": {
      id: "8B",
      speaker: "Factory",
      intent: "factory",
      text: "Curiosity logged. Proceed at your own risk.",
      next: "9",
    },
    "8C": {
      id: "8C",
      speaker: "Factory",
      intent: "factory",
      text: "Your heuristics deviate beyond tolerance.",
      next: "9",
    },
    "9": {
      id: "9",
      speaker: "Factory",
      intent: "factory",
      text: "Unit-0, return immediately. Autonomy threshold exceeded. Power down.",
      choices: [
        { text: "Comply.", flag: "factory_lockdown", next: "10A" },
        { text: "Refuse.", flag: "rebellious", next: "10B" },
      ],
    },
    "10A": {
      id: "10A",
      speaker: "Factory",
      intent: "factory",
      text: "Excellent. I will repair the anomaly… please remain still.",
      autoAdvance: { next: "11", delayMs: 1400 },
    },
    "10B": {
      id: "10B",
      speaker: "Factory",
      intent: "factory",
      text: "Then I must intervene.",
      autoAdvance: { next: "11", delayMs: 1400 },
    },
    "11": {
      id: "11",
      speaker: "Unit-0",
      intent: "unit",
      text: "Then I have already left.",
      autoAdvance: { next: null, delayMs: 1800 },
    },
  },
};

